#!/usr/bin/env bash
set -euo pipefail

# Local gate runner entrypoint required by OMOC landing
OUT_DIR="artifacts"
mkdir -p "$OUT_DIR"
mkdir -p artifacts/logs

echo "[run_gates] START" | tee artifacts/logs/run_gates.log

## Enforce EXECUTE_DISABLED (kill-switch) - prefer control_plane/EXECUTE_DISABLED
SSOT="control_plane/EXECUTE_DISABLED"
if [ -f "$SSOT" ]; then
  echo "[run_gates] Using repository SSOT $SSOT" | tee -a artifacts/logs/run_gates.log
  cp "$SSOT" ./EXECUTE_DISABLED || true
else
  if [ -f EXECUTE_DISABLED ]; then
    if grep -q "\"allowed\":\s*false" EXECUTE_DISABLED >/dev/null 2>&1; then
      echo "[run_gates] EXECUTE_DISABLED is active — blocking any execute/trading paths" | tee -a artifacts/logs/run_gates.log
    else
      echo "[run_gates] WARNING: EXECUTE_DISABLED present but not set to false" | tee -a artifacts/logs/run_gates.log
    fi
  else
    echo "[run_gates] No EXECUTE_DISABLED file found — creating fail-closed marker" | tee -a artifacts/logs/run_gates.log
    cat > EXECUTE_DISABLED <<'JSON'
{
  "allowed": false,
  "reason": "Fail-closed default created by run_gates"
}
JSON
    echo "created EXECUTE_DISABLED" | tee -a artifacts/logs/run_gates.log
  fi
fi

# run the canonical local gates (uses scripts/gate_all_local.sh)
set +e
bash scripts/gate_all_local.sh > artifacts/logs/gate_all_local.stdout 2>&1
RC=$?
set -e

# Build artifacts JSONs (minimal manifest/evidence_index/gate_report/verdict)
MANIFEST="$OUT_DIR/manifest.json"
EVIDENCE_INDEX="$OUT_DIR/evidence_index.json"
GATE_REPORT="$OUT_DIR/gate_report.json"
VERDICT="$OUT_DIR/verdict.json"

now=$(date -u +%Y%m%dT%H%M%SZ)

cat > "$MANIFEST" <<JSON
{
  "run": "run_gates",
  "timestamp": "${now}",
  "exit_code": ${RC}
}
JSON

# evidence index: point to logs generated by local acceptance
cat > "$EVIDENCE_INDEX" <<JSON
{
  "evidence": [
    "artifacts/logs/gate_all_local.stdout",
    "evidence/_b1/acceptance_console.txt",
    "evidence/_b1/triad.json"
  ]
}
JSON

# gate_report: minimal summary
status="PASS"
if [ $RC -ne 0 ]; then status="FAIL"; fi
cat > "$GATE_REPORT" <<JSON
{
  "status": "${status}",
  "exit_code": ${RC},
  "logs": ["artifacts/logs/gate_all_local.stdout"],
  "notes": "See artifacts/logs for details"
}
JSON

cat > "$VERDICT" <<JSON
{
  "verdict": "${status}",
  "checked_at": "${now}",
  "evidence_index": "${EVIDENCE_INDEX}",
  "gate_report": "${GATE_REPORT}"
}
JSON

echo "[run_gates] FINISH status=${status} rc=${RC}" | tee -a artifacts/logs/run_gates.log

# Final exit follows the real exit code to ensure CI fails when gates truly fail.
echo "[run_gates] EXITING with original rc=${RC}" | tee -a artifacts/logs/run_gates.log
exit ${RC}
