HTTP/2.0 200 OK
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
Cache-Control: private, max-age=60, s-maxage=60
Content-Security-Policy: default-src 'none'
Content-Type: application/json; charset=utf-8
Date: Tue, 03 Feb 2026 09:52:00 GMT
Etag: W/"23e4a3168626583339737475b17160f437180eea0a23ceaed11c0214b9b10292"
Github-Authentication-Token-Expiration: 2026-02-03 21:17:26 UTC
Referrer-Policy: origin-when-cross-origin, strict-origin-when-cross-origin
Server: github.com
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Vary: Accept, Authorization, Cookie, X-GitHub-OTP,Accept-Encoding, Accept, X-Requested-With
X-Accepted-Github-Permissions: metadata=read
X-Accepted-Oauth-Scopes: repo
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Github-Api-Version-Selected: 2022-11-28
X-Github-Media-Type: github.v3; format=json
X-Github-Request-Id: A009:98C19:1AB0E4:1D9D82:6981C540
X-Oauth-Client-Id: Iv1.ad5f73e593b03f40
X-Oauth-Scopes: 
X-Ratelimit-Limit: 50000
X-Ratelimit-Remaining: 49955
X-Ratelimit-Reset: 1770113848
X-Ratelimit-Resource: core
X-Ratelimit-Used: 45
X-Xss-Protection: 0

{"id":12397484,"name":"gates","target":"branch","source_type":"Repository","source":"shw097/spartoi-project-2","enforcement":"active","conditions":{"ref_name":{"exclude":[],"include":["~DEFAULT_BRANCH"]}},"rules":[{"type":"deletion"},{"type":"non_fast_forward"},{"type":"required_status_checks","parameters":{"strict_required_status_checks_policy":true,"do_not_enforce_on_create":false,"required_status_checks":[{"context":"gates","integration_id":15368}]}}],"node_id":"RRS_lACqUmVwb3NpdG9yec5Eb1R6zgC9K6w","created_at":"2026-02-03T08:14:03.522Z","updated_at":"2026-02-03T08:14:03.576Z","bypass_actors":[],"current_user_can_bypass":"never","_links":{"self":{"href":"https://api.github.com/repos/shw097/spartoi-project-2/rulesets/12397484"},"html":{"href":"https://github.com/shw097/spartoi-project-2/rules/12397484"}}}